backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "testimonial"
    label: "Testimonial"
    folder: "content/testimonials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string", required: false}
      - {label: "Organisation", name: "organisation", widget: "string", required: false}
      - {label: "Testimonial", name: "testimonial", widget: "markdown"}
      - {label: "Sequence", name: "sequence", widget: "number", valueType: "int", required: false}
  - name: "external-media"
    label: "External Media"
    folder: "content/external"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Sequence", name: "sequence", widget: "number", valueType: "int", required: false}
  - name: "event"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Event Title", name: "title", widget: "string"}
      - {label: "Event Link", name: "link", widget: "string"}
      - {label: "Event Date", name: "date", widget: "datetime"}
  - name: "page"
    label: "Page"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog"
    label: "Blog Post"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Post Date", name: "post_date", widget: "datetime"}
      - {label: "Feature Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Featured Article", name: "featured", widget: "boolean", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: false}
      - {label: "Authors", name: "authors", widget: "string"}
      - {label: "Post Content", name: "body", widget: "markdown"}
  - name: "newsletter"
    label: "Newsletter"
    folder: "content/newsletter"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publication Date", name: "publication_date", widget: "datetime"}
      - {label: "Founders Headline", name: "founders", widget: "text"}
      - {label: "Insights", name: "insights", widget: "markdown"}
      - {label: "Coming Up", name: "coming_up", widget: "markdown"}
      - {label: "Coming Up Link", name: "coming_up_link", widget: "string"}
  - name: "organisation"
    label: "Organisation"
    folder: "content/organisations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Organisation", name: "partner", widget: "string"}