backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "nudge"
    label: "Inclusion Nudge"
    folder: "nudges"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Path", name: "path"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
<<<<<<< HEAD
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: "false"}
=======
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
>>>>>>> 50709324e825e79ddbf06bc6667970ac1b801f84
      - {label: "Nudge", name: "nudge", widget: "markdown"}